### ISSUE TITLE
Watchprovider display issue

### ISSUE THREAD

**Issue by robert-zsolt-nagy** [robert-zsolt-nagy/movies-to-watch#13]
There is a display issue in case there is no streaming provider and there are many buy or rent options for a given movie.
It is unaffected by breakpoint.

![Image](https://github.com/robert-zsolt-nagy/movies-to-watch/assets/157964780/c1f5eeb9-068d-47df-acfd-24cc4f78e52f)

**Comment by nagyesta** [comment]
This is the cause of the issue:
![image](https://github.com/robert-zsolt-nagy/movies-to-watch/assets/308406/d9ddc4ba-2f84-4f1b-b676-12ebfa2e0cc9)
